apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
  annotations:
    argocd-image-updated.argoproj.io/image-list: jasjeet1009/devops-automation:v1
  labels:
    app: spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: spring-boot-k8s
        image: jasjeet1009/devops-automation:
        ports:
        - containerPort: 80